services:
  ntopng:
    build:
      context: ../..
      dockerfile: Dockerfile.ntopng
    hostname: ntop
    container_name: ntop
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /etc/ntopng.license:/etc/ntopng.license:ro
      - ntopng_redis:/var/lib/redis
    command:
      - -i
      - tcp://*:5556c
      - -F
      - clickhouse;clickhouse@9000,9004;ntopng;default;
      - --disable-login
      - "1"
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse
    container_name: clickhouse
    restart: always
    ports:
      - 9000:9000
      - 9004:9004
      - 8123:8123
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server

volumes:
  clickhouse_data:
  clickhouse_logs:
  ntopng_redis:
